// GioHomeStudio — Terms of Use (clean, professional, owner-protective)
import { ds } from "../../../lib/designSystem";

const h2Style: React.CSSProperties = {
  fontSize: 15,
  fontWeight: 700,
  color: ds.color.ink,
  marginTop: 28,
  marginBottom: 8,
  fontFamily: ds.font.sans,
  letterSpacing: "-0.01em",
};

const pStyle: React.CSSProperties = {
  fontSize: 13,
  color: ds.color.ink2,
  lineHeight: 1.8,
  marginBottom: 10,
  fontFamily: ds.font.sans,
};

export default function TermsPage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: ds.color.paper,
        fontFamily: ds.font.sans,
        padding: "40px 24px 80px",
      }}
    >
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <a
          href="/"
          style={{
            fontSize: 12,
            color: ds.color.lilac,
            textDecoration: "none",
            fontFamily: ds.font.mono,
          }}
        >
          &larr; Back to GioHomeStudio
        </a>

        <h1
          style={{
            fontSize: 24,
            fontWeight: 800,
            color: ds.color.ink,
            marginTop: 20,
            marginBottom: 6,
            letterSpacing: "-0.03em",
            fontFamily: ds.font.sans,
          }}
        >
          Terms of Use
        </h1>
        <p
          style={{
            fontSize: 12,
            color: ds.color.mute2,
            marginBottom: 36,
            fontFamily: ds.font.mono,
          }}
        >
          Version 1.0 &middot; Effective from first use
        </p>

        <h2 style={h2Style}>1. What GioHomeStudio Is</h2>
        <p style={pStyle}>GioHomeStudio is an AI-assisted content creation and publishing platform. It uses third-party AI systems to help you create video, audio, image, and text content based on your instructions. AI systems can produce output that is inaccurate or unexpected — always review your content before publishing.</p>

        <h2 style={h2Style}>2. You Are the Publisher</h2>
        <p style={pStyle}>When you approve content for publication, you are the publisher of record. This means you are responsible for making sure your content is accurate, appropriate, and does not violate any laws or platform rules. This applies whether the content was written by you or generated by AI.</p>

        <h2 style={h2Style}>3. Review Before Publishing</h2>
        <p style={pStyle}>All content must be reviewed by you before it is published. Watch, read, and check everything. The platform will always ask for your approval before posting anything publicly.</p>

        <h2 style={h2Style}>4. Your Content Rights</h2>
        <p style={pStyle}>You confirm that you own or have permission to use all media, images, videos, voices, and materials you upload. If your content includes another person, you confirm you have their permission. Do not upload content you do not have rights to use.</p>

        <h2 style={h2Style}>5. Voice and Likeness</h2>
        <p style={pStyle}>If you use voice cloning or AI likeness features, you confirm the voice or image belongs to you, or you have explicit permission from the person. Impersonating others without consent is not allowed.</p>

        <h2 style={h2Style}>6. Prohibited Content</h2>
        <p style={pStyle}>You may not use the platform to create content that is defamatory, fraudulent, sexually explicit, violent, hateful, or that impersonates another person. Content involving minors in inappropriate contexts is strictly prohibited and will result in immediate account termination.</p>

        <h2 style={h2Style}>7. AI Disclosure</h2>
        <p style={pStyle}>Some platforms require you to disclose when content is AI-generated. It is your responsibility to make that disclosure where required.</p>

        <h2 style={h2Style}>8. Platform Connections</h2>
        <p style={pStyle}>When you connect social accounts (YouTube, Instagram, TikTok, etc.), you authorize GioHomeStudio to post on your behalf after you approve the content. You can disconnect any account at any time. No passwords are stored.</p>

        <h2 style={h2Style}>9. Credits and Payments</h2>
        <p style={pStyle}>The platform uses a credit system for paid features. Credits are only used after you approve a generation or publish action. No silent charges.</p>

        <h2 style={h2Style}>10. Service Availability</h2>
        <p style={pStyle}>The platform is provided as-is. We do not guarantee uninterrupted service, that all content will be accepted by social platforms, or that AI output will always be suitable for publication.</p>

        <h2 style={h2Style}>11. Limitation of Liability</h2>
        <p style={pStyle}>GioHomeStudio and its developers are not liable for content you approve and publish, or for third-party platform actions such as account suspension. Your decision to publish is your responsibility.</p>

        <h2 style={h2Style}>12. Account Suspension</h2>
        <p style={pStyle}>We may suspend or terminate accounts that violate these terms, create prohibited content, or misuse platform features.</p>

        <h2 style={h2Style}>13. Sound and Music Ownership</h2>
        <p style={pStyle}>Custom-generated sound created inside GioHomeStudio may be used by the customer subject to GHS terms and any applicable third-party provider terms. For imported third-party sounds, the customer is responsible for complying with applicable license, attribution, and usage restrictions. GHS may provide attribution assistance, but the customer remains responsible for lawful final use.</p>
        <p style={pStyle}>GioHomeStudio classifies sounds into three usage buckets: (1) Fully owned or GHS-internal sounds — always allowed; (2) CC0 / public domain sounds — allowed, no attribution required; (3) CC BY sounds — allowed only with proper attribution, which GHS can auto-generate. Sounds with CC BY-NC licenses or unknown licenses are blocked from commercial production flows.</p>
        <p style={pStyle}>GioHomeStudio does not guarantee that generated or imported sounds are free from all third-party claims. The customer should verify usage rights independently when creating content for commercial distribution.</p>

        <h2 style={h2Style}>14. Governing Law</h2>
        <p style={pStyle}>These terms are governed by the laws of the Federal Republic of Nigeria.</p>

        <div
          style={{
            borderTop: `1px solid ${ds.color.line}`,
            marginTop: 40,
            paddingTop: 16,
          }}
        >
          <p
            style={{
              fontSize: 11,
              color: ds.color.mute2,
              lineHeight: 1.8,
              fontFamily: ds.font.mono,
            }}
          >
            AI-assisted content. Human approval required before posting. You are responsible for content you approve and publish.
          </p>
        </div>
      </div>
    </div>
  );
}
