"use client";

import Link from "next/link";

const DEMO_VIDEOS = [
  { src: "/api/media/intro/demo-commercial-oj.mp4", label: "Commercial Maker", desc: "Orange juice promo — AI-generated product ad" },
  { src: "/api/media/intro/demo-story-mode.mp4", label: "Story Mode", desc: "Episodic storytelling with narration & music" },
  { src: "/api/media/intro/demo-short-reel.mp4", label: "Short Reel", desc: "Quick vertical reel for social platforms" },
  { src: "/api/media/intro/hero-brave.mp4", label: "AI Video Generation", desc: "Cinematic scenes from a text prompt" },
  { src: "/api/media/intro/hero-maintain.mp4", label: "AI Characters", desc: "Consistent characters across scenes" },
  { src: "/api/media/intro/demo-property.mp4", label: "Property Ads", desc: "Real estate promo with overlays & voice" },
];

const FEATURES = [
  { icon: "🎬", title: "7 Output Modes", desc: "Free, Reel, Series, Commercial, Image-to-Video, Text-to-Audio, Motion Transfer" },
  { icon: "🎙", title: "5 Voice Providers", desc: "ElevenLabs, Cartesia, Fish Audio, Piper, and more" },
  { icon: "🎵", title: "Music Studio & DJ", desc: "AI generation, stock library, SFX, beat viz, mixing" },
  { icon: "📊", title: "Analytics & A/B", desc: "Track performance, test variations, learn what works" },
  { icon: "📅", title: "Content Calendar", desc: "Plan, schedule, and manage across platforms" },
  { icon: "🚀", title: "5 Publishing Platforms", desc: "YouTube, Instagram, TikTok, Facebook, Telegram" },
];

export default function HomePage() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg, #080818)" }}>
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        {/* Background video (muted, looping) */}
        <div className="absolute inset-0 opacity-20">
          <video
            src="/api/media/intro/hero-brave.mp4"
            autoPlay muted loop playsInline
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0" style={{ background: "linear-gradient(to bottom, rgba(8,8,24,0.6), rgba(8,8,24,1))" }} />
        </div>

        <div className="relative z-10 flex flex-col items-center justify-center text-center px-6 pt-20 pb-16">
          <h1 className="text-5xl md:text-6xl font-bold text-white mb-4 tracking-tight">
            Gio<span style={{ color: "var(--accent, #7c5cfc)" }}>Home</span>Studio
          </h1>
          <p className="text-gray-400 text-lg md:text-xl max-w-2xl mb-2">
            AI-powered video content studio.
          </p>
          <p className="text-gray-500 text-sm max-w-xl mb-8">
            Generate, review, approve, publish, and track video content across multiple platforms — from one system.
          </p>
          <div className="flex gap-4">
            <Link
              href="/dashboard"
              className="px-8 py-3.5 rounded-xl font-semibold text-white text-sm transition-all hover:scale-105"
              style={{ background: "var(--accent, #7c5cfc)", boxShadow: "0 4px 24px rgba(124,92,252,0.4)" }}
            >
              Open Studio
            </Link>
            <Link
              href="/dashboard/review"
              className="px-8 py-3.5 rounded-xl font-semibold text-gray-300 text-sm border border-gray-700 hover:border-gray-500 transition-colors"
            >
              Review Queue
            </Link>
          </div>
        </div>
      </section>

      {/* Demo Videos Grid */}
      <section className="max-w-6xl mx-auto px-6 pb-16">
        <h2 className="text-xl font-bold text-white mb-1 text-center">See What It Creates</h2>
        <p className="text-xs text-gray-500 mb-8 text-center">Real outputs generated by GioHomeStudio</p>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          {DEMO_VIDEOS.map((v) => (
            <div key={v.label} className="group relative rounded-xl overflow-hidden border border-gray-800 hover:border-[#7c5cfc]/50 transition-all">
              <video
                src={v.src}
                muted loop playsInline
                className="w-full aspect-[9/16] object-cover"
                onMouseEnter={e => (e.currentTarget as HTMLVideoElement).play()}
                onMouseLeave={e => { const el = e.currentTarget as HTMLVideoElement; el.pause(); el.currentTime = 0; }}
              />
              <div className="absolute bottom-0 left-0 right-0 p-3" style={{ background: "linear-gradient(transparent, rgba(0,0,0,0.85))" }}>
                <p className="text-white text-sm font-semibold">{v.label}</p>
                <p className="text-gray-400 text-[10px]">{v.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Features Grid */}
      <section className="max-w-5xl mx-auto px-6 pb-20">
        <h2 className="text-xl font-bold text-white mb-6 text-center">Built-In Everything</h2>
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          {FEATURES.map((f) => (
            <div key={f.title} className="rounded-xl p-4 border border-gray-800 hover:border-[#7c5cfc]/30 transition-colors" style={{ background: "rgba(18,18,30,0.8)" }}>
              <span className="text-2xl">{f.icon}</span>
              <p className="text-white text-sm font-semibold mt-2">{f.title}</p>
              <p className="text-gray-500 text-[10px] mt-0.5">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="text-center pb-16 px-6">
        <Link
          href="/dashboard"
          className="inline-block px-10 py-4 rounded-xl font-bold text-white text-sm transition-all hover:scale-105"
          style={{ background: "var(--accent, #7c5cfc)", boxShadow: "0 4px 24px rgba(124,92,252,0.3)" }}
        >
          Start Creating
        </Link>
      </section>
    </div>
  );
}
