// GET /api/templates — visual, usable templates like CapCut
// Each template has a pre-filled prompt, settings, and visual style

import { NextResponse } from "next/server";

const TEMPLATES = [
  // ── Real Estate (5) ──
  {
    id: "re_tour_vertical",
    name: "Property Tour Reel",
    category: "Real Estate",
    thumbnail: "",
    preview: "Luxury apartment walkthrough with narration, music, and price overlay",
    prompt: "Cinematic walkthrough of a modern luxury apartment. Show living room, bedroom, kitchen, and bathroom. Warm lighting, smooth camera movement, soft background music.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 30, voiceEnabled: true, musicGenre: "ambient" },
    tags: ["property", "tour", "vertical", "reel"],
    popular: true,
  },
  {
    id: "re_listing_banner",
    name: "Property Listing Banner",
    category: "Real Estate",
    thumbnail: "",
    preview: "Wide banner with property exterior, key features, and price badge",
    prompt: "Modern house exterior at golden hour. Clean sky, manicured lawn, warm glow from windows. Cinematic, professional real estate photography style.",
    settings: { mode: "text_to_image", aspectRatio: "16:9" },
    tags: ["property", "banner", "listing"],
  },
  {
    id: "re_before_after",
    name: "Before & After Renovation",
    category: "Real Estate",
    thumbnail: "",
    preview: "Split-screen before/after renovation with dramatic reveal",
    prompt: "Split screen renovation reveal. Left side shows old, worn-out room. Right side reveals the same room fully renovated with modern furniture, fresh paint, and new lighting. Dramatic reveal transition.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 15 },
    tags: ["renovation", "before-after", "reveal"],
  },
  {
    id: "re_shortlet_promo",
    name: "Shortlet Promo Reel",
    category: "Real Estate",
    thumbnail: "",
    preview: "Quick showcase of amenities with prices and booking CTA",
    prompt: "Shortlet apartment showcase reel. Smart TV with Netflix, clean white bedsheets, modern bathroom, fully equipped kitchen, 24/7 security, free parking. Fast-paced cuts with text overlays showing each amenity. End with price and WhatsApp contact.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 20, voiceEnabled: true },
    tags: ["shortlet", "promo", "amenities"],
    popular: true,
  },
  {
    id: "re_agent_intro",
    name: "Real Estate Agent Intro",
    category: "Real Estate",
    thumbnail: "",
    preview: "Professional agent introduction with contact details",
    prompt: "Professional real estate agent standing in front of a luxury property. Confident pose, business attire. Text overlay with name, title, and contact information. Clean, premium look.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 10 },
    tags: ["agent", "intro", "professional"],
  },

  // ── Product Ads (5) ──
  {
    id: "prod_showcase_360",
    name: "Product 360 Showcase",
    category: "Product Ads",
    thumbnail: "",
    preview: "Product rotating on clean background with features appearing",
    prompt: "Premium product showcase. Product slowly rotates on a clean white studio background. Soft studio lighting, subtle shadow. Feature text appears one by one. Professional e-commerce style.",
    settings: { mode: "text_to_video", aspectRatio: "1:1", duration: 15 },
    tags: ["product", "360", "showcase", "ecommerce"],
    popular: true,
  },
  {
    id: "prod_flash_sale",
    name: "Flash Sale Countdown",
    category: "Product Ads",
    thumbnail: "",
    preview: "Urgent flash sale with countdown timer, bold prices, and red accents",
    prompt: "Flash sale advertisement. Bold red and white design. Product images flash with original price crossed out and sale price highlighted. Countdown timer ticking. Urgent energy, fast cuts. 'LIMITED TIME ONLY' text pulses.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 15, musicGenre: "upbeat" },
    tags: ["sale", "flash", "countdown", "urgent"],
  },
  {
    id: "prod_unboxing",
    name: "Unboxing Reveal",
    category: "Product Ads",
    thumbnail: "",
    preview: "Cinematic unboxing with dramatic lighting and slow-motion reveal",
    prompt: "Cinematic product unboxing. Hands slowly open a premium box. Dramatic lighting from inside the box illuminates the product. Slow motion reveal. Dust particles in the air. Premium luxury feel.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 20 },
    tags: ["unboxing", "reveal", "luxury"],
  },
  {
    id: "prod_comparison",
    name: "Product Comparison",
    category: "Product Ads",
    thumbnail: "",
    preview: "Side-by-side comparison highlighting your product's advantages",
    prompt: "Product comparison video. Split screen showing 'Others' on left (dull, basic) vs 'Ours' on right (premium, detailed, superior). Checkmarks appear next to our features. Clean professional look.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 20 },
    tags: ["comparison", "vs", "features"],
  },
  {
    id: "prod_testimonial",
    name: "Customer Testimonial",
    category: "Product Ads",
    thumbnail: "",
    preview: "Happy customer quote with product image and star rating",
    prompt: "Customer testimonial style. Quote text appears on screen with 5-star rating. Product image in background, slightly blurred. Clean, trustworthy design. Customer name and verified badge at bottom.",
    settings: { mode: "text_to_image", aspectRatio: "1:1" },
    tags: ["testimonial", "review", "trust"],
  },

  // ── Social Media (5) ──
  {
    id: "social_motivational",
    name: "Motivational Quote Reel",
    category: "Social Media",
    thumbnail: "",
    preview: "Powerful quote with cinematic background and dramatic music",
    prompt: "Motivational video. Cinematic wide shots of nature — mountains, ocean, sunrise. Powerful quote text appears word by word with dramatic impact. Deep bass music. Inspirational and energizing mood.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 15, musicGenre: "cinematic" },
    tags: ["motivation", "quote", "reel", "inspirational"],
    popular: true,
  },
  {
    id: "social_this_or_that",
    name: "This or That Poll",
    category: "Social Media",
    thumbnail: "",
    preview: "Interactive this-or-that format with two options side by side",
    prompt: "This or That interactive content. Split screen showing two choices. Colorful, playful design. Question at top. Option A on left, Option B on right. Fun, engaging social media style.",
    settings: { mode: "text_to_image", aspectRatio: "9:16" },
    tags: ["poll", "interactive", "engagement"],
  },
  {
    id: "social_countdown",
    name: "Launch Countdown",
    category: "Social Media",
    thumbnail: "",
    preview: "Coming soon / launch countdown with hype building",
    prompt: "Product launch countdown. Dark background with neon glow. Numbers counting down 3, 2, 1. Reveal flash. 'Coming Soon' or 'Available Now' with product silhouette. Hype and anticipation energy.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 10 },
    tags: ["launch", "countdown", "hype", "coming-soon"],
  },
  {
    id: "social_tutorial_steps",
    name: "Step-by-Step Tutorial",
    category: "Social Media",
    thumbnail: "",
    preview: "Numbered steps with visual demonstrations, carousel or reel style",
    prompt: "Step by step tutorial reel. Clean numbered steps (Step 1, Step 2, Step 3). Each step has a clear visual demonstration. Simple, minimal design. Easy to follow. Educational content style.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 30 },
    tags: ["tutorial", "steps", "how-to", "educational"],
  },
  {
    id: "social_meme_reaction",
    name: "Reaction / Meme Format",
    category: "Social Media",
    thumbnail: "",
    preview: "Meme-style format with top text, reaction, and punchline",
    prompt: "Funny reaction meme video. Top text sets up the situation. Character reacts dramatically. Bottom text delivers the punchline. Quick, snappy, viral format. Internet humor style.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 8 },
    tags: ["meme", "reaction", "funny", "viral"],
  },

  // ── Food & Restaurant (5) ──
  {
    id: "food_menu_reel",
    name: "Menu Showcase Reel",
    category: "Food & Restaurant",
    thumbnail: "",
    preview: "Mouth-watering menu items with prices and restaurant branding",
    prompt: "Restaurant menu showcase reel. Close-up shots of delicious food plates. Steam rising, garnishes glistening. Each dish name and price appears as overlay. Warm, appetizing lighting. Soft jazz background.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 25, musicGenre: "jazz" },
    tags: ["food", "menu", "restaurant"],
  },
  {
    id: "food_recipe_short",
    name: "30-Second Recipe",
    category: "Food & Restaurant",
    thumbnail: "",
    preview: "Quick recipe with ingredients appearing and fast cooking montage",
    prompt: "Quick recipe video. Ingredients laid out neatly on marble counter. Fast-paced cooking montage with top-down shots. Sizzling pan, chopping, plating. Final dish reveal with steam. Recipe name overlay.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 30 },
    tags: ["recipe", "cooking", "quick"],
    popular: true,
  },
  {
    id: "food_delivery_promo",
    name: "Delivery Promo",
    category: "Food & Restaurant",
    thumbnail: "",
    preview: "Food delivery ad with ordering process and delivery animation",
    prompt: "Food delivery promo. Phone screen showing app ordering. Rider picks up food. Delivery to door. Happy customer opens container. Steaming delicious food. 'Order Now' CTA with discount code.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 15 },
    tags: ["delivery", "food", "promo", "order"],
  },
  {
    id: "food_special_offer",
    name: "Daily Special Offer",
    category: "Food & Restaurant",
    thumbnail: "",
    preview: "Today's special with large food image, original and sale price",
    prompt: "Daily special offer. Large appetizing food image centered. 'TODAY ONLY' badge. Original price crossed out, sale price highlighted in red. Restaurant logo. Clean, bold design that makes you hungry.",
    settings: { mode: "text_to_image", aspectRatio: "1:1" },
    tags: ["special", "offer", "daily", "deal"],
  },
  {
    id: "food_review_style",
    name: "Food Review Style",
    category: "Food & Restaurant",
    thumbnail: "⭐",
    preview: "First-person food review with ratings and commentary overlay",
    prompt: "Food review style video. First bite close-up. Reaction shot. Star rating appears. Review text scrolls. Multiple dishes sampled. Overall verdict at end. Casual, authentic reviewer style.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 30 },
    tags: ["review", "food", "rating", "authentic"],
  },

  // ── Entertainment & Story (5) ──
  {
    id: "story_horror_hook",
    name: "Horror Story Hook",
    category: "Entertainment",
    thumbnail: "",
    preview: "Creepy opening scene with suspense music and dark visuals",
    prompt: "Horror story opening. Dark abandoned building at night. Camera slowly pushes through a creaking door. Flickering lights. Eerie shadows. Suspenseful music building. Sudden cut to black with text: 'What happened next will shock you...'",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 15, musicGenre: "suspense" },
    tags: ["horror", "story", "hook", "suspense"],
  },
  {
    id: "story_action_scene",
    name: "Action Scene Clip",
    category: "Entertainment",
    thumbnail: "",
    preview: "Fast-paced action sequence with dramatic cuts",
    prompt: "Intense action scene. Character running through urban environment. Quick cuts, dramatic angles. Explosions in background. Slow motion jump. Epic orchestral music. Cinematic color grading — teal and orange.",
    settings: { mode: "text_to_video", aspectRatio: "16:9", duration: 15, musicGenre: "epic" },
    tags: ["action", "scene", "cinematic", "epic"],
  },
  {
    id: "story_romantic_moment",
    name: "Romantic Moment",
    category: "Entertainment",
    thumbnail: "",
    preview: "Beautiful romantic scene with soft lighting and emotional music",
    prompt: "Romantic moment. Two people standing on a bridge at sunset. Soft golden light, gentle breeze. Slow motion. Warm color grading. Emotional piano music. Petals floating in the air.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 15, musicGenre: "romantic" },
    tags: ["romance", "love", "emotional", "sunset"],
  },
  {
    id: "story_african_folktale",
    name: "African Folktale",
    category: "Entertainment",
    thumbnail: "",
    preview: "Animated-style African folktale with narration and traditional music",
    prompt: "African folktale animation. Village scene with traditional huts and baobab trees. Elder storyteller sitting by fire. Colorful traditional clothing. Vibrant sunset. Traditional drum music. Rich, warm colors.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 30, voiceEnabled: true, musicGenre: "african" },
    tags: ["african", "folktale", "story", "culture"],
    popular: true,
  },
  {
    id: "story_mystery_cliffhanger",
    name: "Mystery Cliffhanger",
    category: "Entertainment",
    thumbnail: "",
    preview: "Mystery scene ending with dramatic cliffhanger for next episode",
    prompt: "Mystery scene. Detective examining evidence in dim room. Close-up of clue being discovered. Character turns slowly. Dramatic music builds. Screen goes black. 'To be continued...' appears. Part 1 tag.",
    settings: { mode: "text_to_video", aspectRatio: "9:16", duration: 20, musicGenre: "suspense" },
    tags: ["mystery", "cliffhanger", "series", "detective"],
  },

  // ── Intro/Outro (5) ──
  {
    id: "io_youtube_intro",
    name: "YouTube Channel Intro",
    category: "Intro / Outro",
    thumbnail: "▶️",
    preview: "Animated logo reveal with channel name and subscribe reminder",
    prompt: "YouTube channel intro. Dark background, logo animates in with particle effects. Channel name appears with glow. 'Subscribe' bell icon pulses. Short, punchy, 3 seconds. Professional yet energetic.",
    settings: { mode: "text_to_video", aspectRatio: "16:9", duration: 3 },
    tags: ["youtube", "intro", "channel", "logo"],
  },
  {
    id: "io_podcast_intro",
    name: "Podcast Episode Intro",
    category: "Intro / Outro",
    thumbnail: "",
    preview: "Audio waveform animation with podcast name and episode number",
    prompt: "Podcast intro animation. Sound waveform animating in center. Podcast name and logo appear. Episode number fades in. Dark background with accent color glow. Professional audio show style.",
    settings: { mode: "text_to_video", aspectRatio: "16:9", duration: 5, musicGenre: "podcast" },
    tags: ["podcast", "intro", "audio", "episode"],
  },
  {
    id: "io_subscribe_outro",
    name: "Subscribe + Like Outro",
    category: "Intro / Outro",
    thumbnail: "",
    preview: "End screen with subscribe button, like, and next video pointer",
    prompt: "YouTube end screen outro. 'Subscribe' button animation with bell icon. 'Like this video' with thumbs up. Two video thumbnail placeholders for next video. Clean animated design.",
    settings: { mode: "text_to_video", aspectRatio: "16:9", duration: 6 },
    tags: ["outro", "subscribe", "like", "end-screen"],
  },
  {
    id: "io_business_intro",
    name: "Business Presentation Intro",
    category: "Intro / Outro",
    thumbnail: "",
    preview: "Clean corporate intro with company logo and tagline",
    prompt: "Corporate presentation intro. Clean white and blue design. Company logo draws itself on screen. Tagline appears underneath. Professional, trustworthy, corporate mood. Subtle ambient music.",
    settings: { mode: "text_to_video", aspectRatio: "16:9", duration: 4 },
    tags: ["business", "corporate", "presentation", "intro"],
  },
  {
    id: "io_credits_scroll",
    name: "Movie Credits Scroll",
    category: "Intro / Outro",
    thumbnail: "",
    preview: "Scrolling credits with star field background like movie endings",
    prompt: "Movie credits outro. Star field background slowly moving. Credits text scrolling upward. Cast names, crew, 'Produced by', 'Directed by'. Orchestral music fading. Classic cinema ending feel.",
    settings: { mode: "text_to_video", aspectRatio: "16:9", duration: 15, musicGenre: "cinematic" },
    tags: ["credits", "movie", "scroll", "ending"],
  },
];

export async function GET() {
  return NextResponse.json({
    templates: TEMPLATES,
    categories: [...new Set(TEMPLATES.map(t => t.category))],
    popular: TEMPLATES.filter(t => t.popular),
    total: TEMPLATES.length,
  });
}
