// GioHomeStudio — Sound Licensing Policy v1.0 (2026-04-26)
import { ds } from "../../../lib/designSystem";

const h2Style: React.CSSProperties = {
  fontSize: 15,
  fontWeight: 700,
  color: ds.color.ink,
  marginTop: 28,
  marginBottom: 8,
  fontFamily: ds.font.sans,
  letterSpacing: "-0.01em",
};

const pStyle: React.CSSProperties = {
  fontSize: 13,
  color: ds.color.ink2,
  lineHeight: 1.8,
  marginBottom: 10,
  fontFamily: ds.font.sans,
};

const liStyle: React.CSSProperties = {
  fontSize: 13,
  color: ds.color.ink2,
  lineHeight: 1.8,
  marginBottom: 6,
  fontFamily: ds.font.sans,
  marginLeft: 16,
};

type BucketRow = {
  bucket: string;
  allowed: string;
  attribution: string;
  commercial: string;
};

const buckets: BucketRow[] = [
  { bucket: "Owned / GHS internal", allowed: "Yes", attribution: "No", commercial: "Yes" },
  { bucket: "CC0 / Public Domain", allowed: "Yes", attribution: "Optional", commercial: "Yes" },
  { bucket: "CC BY", allowed: "Yes", attribution: "Required — auto-generated by GHS", commercial: "Yes" },
  { bucket: "CC BY-NC", allowed: "No — blocked from commercial flows", attribution: "N/A", commercial: "No" },
  { bucket: "Unknown license", allowed: "No — blocked until verified", attribution: "N/A", commercial: "No" },
];

export default function SoundLicensingPage() {
  return (
    <div
      style={{
        minHeight: "100vh",
        background: ds.color.paper,
        fontFamily: ds.font.sans,
        padding: "40px 24px 80px",
      }}
    >
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <a
          href="/"
          style={{
            fontSize: 12,
            color: ds.color.lilac,
            textDecoration: "none",
            fontFamily: ds.font.mono,
          }}
        >
          &larr; Back to GioHomeStudio
        </a>

        <h1
          style={{
            fontSize: 24,
            fontWeight: 800,
            color: ds.color.ink,
            marginTop: 20,
            marginBottom: 6,
            letterSpacing: "-0.03em",
            fontFamily: ds.font.sans,
          }}
        >
          Sound Licensing Policy
        </h1>
        <p
          style={{
            fontSize: 12,
            color: ds.color.mute2,
            marginBottom: 36,
            fontFamily: ds.font.mono,
          }}
        >
          Version 1.0 &middot; Effective Date: 2026-04-26
        </p>

        <div
          style={{
            background: ds.color.alert,
            border: `1px solid ${ds.color.line2}`,
            borderRadius: ds.radius.sm,
            padding: "12px 16px",
            marginBottom: 28,
          }}
        >
          <p style={{ ...pStyle, marginBottom: 0, color: ds.color.mute, fontSize: 12 }}>
            This document is a product legal draft and is not a substitute for advice from a qualified lawyer.
            Contact: legal@giohomestudio.com — Jurisdiction: Federal Republic of Nigeria.
          </p>
        </div>

        <h2 style={h2Style}>1. Introduction</h2>
        <p style={pStyle}>Sound is a core component of content produced on the GioHomeStudio platform. This Sound Licensing Policy explains the rules governing the use of music, sound effects (SFX), and audio content generated or uploaded through the platform. As publisher of record for all content you approve, you are responsible for ensuring all audio in your published content is properly licensed for its intended use.</p>

        <h2 style={h2Style}>2. License Classification System</h2>
        <p style={pStyle}>GioHomeStudio classifies all sounds into usage buckets. The platform enforces these buckets at the assembly stage to prevent unlicensed use in production content:</p>

        <div style={{ overflowX: "auto", marginBottom: 20 }}>
          <table
            style={{
              width: "100%",
              borderCollapse: "collapse",
              fontSize: 12,
              fontFamily: ds.font.sans,
            }}
          >
            <thead>
              <tr>
                {["Bucket", "Allowed in Production?", "Attribution Required?", "Commercial Use?"].map((h) => (
                  <th
                    key={h}
                    style={{
                      textAlign: "left",
                      padding: "8px 10px",
                      background: ds.color.card,
                      color: ds.color.mute,
                      borderBottom: `1px solid ${ds.color.line2}`,
                      fontFamily: ds.font.mono,
                      fontSize: 11,
                    }}
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {buckets.map((row, i) => (
                <tr key={i}>
                  {[row.bucket, row.allowed, row.attribution, row.commercial].map((cell, j) => (
                    <td
                      key={j}
                      style={{
                        padding: "8px 10px",
                        color: j === 0 ? ds.color.ink : ds.color.ink2,
                        borderBottom: `1px solid ${ds.color.line}`,
                        verticalAlign: "top",
                      }}
                    >
                      {cell}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <h2 style={h2Style}>3. Platform Stock Library</h2>
        <p style={pStyle}>GioHomeStudio includes a curated stock library of SFX and music tracks. Current sources include:</p>
        <ul style={{ paddingLeft: 20, margin: "0 0 16px 0" }}>
          <li style={liStyle}><strong>Pixabay Free Music and SFX Library</strong> — Licensed under the Pixabay Content License, which permits free commercial and non-commercial use without attribution requirements.</li>
          <li style={liStyle}>Other stock content added to the library will be disclosed in updated versions of this policy and within the asset metadata in the platform.</li>
        </ul>

        <h2 style={h2Style}>4. AI-Generated Sound</h2>
        <p style={pStyle}>Music and SFX generated through AI providers on the platform (including Kie.ai, Suno, MuAPI, and others) is subject to the applicable provider's terms of service regarding output ownership and commercial use. GioHomeStudio will display the relevant provider terms at the point of generation where available.</p>
        <p style={pStyle}>GioHomeStudio does not guarantee that AI-generated audio is free from all third-party claims, including copyright claims by providers or claims arising from training data. You should verify commercial usage rights independently for high-stakes publications.</p>

        <h2 style={h2Style}>5. Uploaded Third-Party Sound</h2>
        <p style={pStyle}>If you upload audio from a third-party source, you are responsible for verifying and complying with the applicable licence. GioHomeStudio may flag uploads with unverified or incompatible licences and block them from commercial production flows. Uploading music or audio you do not have the right to use may result in content removal, account action, and personal liability to the rights holder.</p>

        <h2 style={h2Style}>6. Attribution Assistance</h2>
        <p style={pStyle}>Where a sound requires attribution under its licence (e.g., CC BY), GioHomeStudio can auto-generate attribution text based on the asset metadata. You are responsible for including that attribution in your final published content. GioHomeStudio's attribution assistance is provided as a convenience and does not constitute legal advice or a guarantee of compliance.</p>

        <h2 style={h2Style}>7. Copyright Takedown</h2>
        <p style={pStyle}>If you receive a copyright claim related to sound used in content produced on this platform, see the DMCA / Copyright Takedown Procedure for the reporting process.</p>

        <h2 style={h2Style}>8. Contact</h2>
        <p style={pStyle}>Sound licensing questions: legal@giohomestudio.com</p>

        <div
          style={{
            borderTop: `1px solid ${ds.color.line}`,
            marginTop: 40,
            paddingTop: 16,
          }}
        >
          <p
            style={{
              fontSize: 11,
              color: ds.color.mute2,
              lineHeight: 1.8,
              fontFamily: ds.font.mono,
            }}
          >
            GioHomeStudio. You are responsible for the sounds in content you approve and publish.
          </p>
        </div>
      </div>
    </div>
  );
}
