// GET /api/overlays/presets — overlay text style presets
// Inspired by Nigerian property ad reels (reference video study)

import { NextResponse } from "next/server";

const PRESETS = [
  {
    id: "property_headline",
    name: "Property Headline",
    description: "Bold red headline with white stroke — like Lagos property ads",
    category: "real_estate",
    layers: [
      {
        type: "text" as const,
        text: "One Bedroom Apartment",
        position: { zone: "top" as const },
        style: {
          fontSize: 48,
          fontWeight: "bold" as const,
          fontFamily: "Impact",
          color: "#FF0000",
          outlineColor: "#FFFFFF",
          outlineWidth: 3,
          shadow: true,
          shadowColor: "#000000",
          outline: true,
          uppercase: false,
        },
        animation: { entrance: "fade_in" as const, startSec: 0.3, durationSec: 99 },
      },
      {
        type: "text" as const,
        text: "📍 Sangotedo, Lekki - Lagos",
        position: { zone: "top" as const, y: 12 },
        style: {
          fontSize: 28,
          fontWeight: "normal" as const,
          fontFamily: "Georgia",
          italic: true,
          color: "#FF0000",
          outlineColor: "#FFFFFF",
          outlineWidth: 2,
          shadow: true,
          outline: true,
        },
        animation: { entrance: "fade_in" as const, startSec: 0.6, durationSec: 99, delay: 0.3 },
      },
    ],
  },
  {
    id: "promo_callout",
    name: "Promo Callout",
    description: "White card with key selling points — sticker style",
    category: "commercial",
    layers: [
      {
        type: "text" as const,
        text: "Smart TV + Netflix",
        position: { zone: "bottom" as const },
        style: {
          fontSize: 24,
          fontWeight: "bold" as const,
          color: "#333333",
          bgColor: "white@0.9",
          bgPadding: 12,
          bgRadius: 8,
          shadow: false,
          outline: false,
        },
        animation: { entrance: "slide_bottom" as const, startSec: 2, durationSec: 4 },
      },
    ],
  },
  {
    id: "price_tag",
    name: "Price Tag",
    description: "Bold price with accent color background",
    category: "commercial",
    layers: [
      {
        type: "text" as const,
        text: "₦60,000/night",
        position: { zone: "bottom" as const },
        style: {
          fontSize: 36,
          fontWeight: "bold" as const,
          color: "#FFFFFF",
          bgColor: "#7c5cfc@0.9",
          bgPadding: 16,
          bgRadius: 12,
          shadow: true,
          outline: false,
        },
        animation: { entrance: "pop_in" as const, startSec: 1, durationSec: 5 },
      },
    ],
  },
  {
    id: "lower_third",
    name: "Lower Third",
    description: "Professional lower-third bar with name and location",
    category: "general",
    layers: [
      {
        type: "text" as const,
        text: "Diolux Apartments",
        position: { zone: "bottom" as const },
        style: {
          fontSize: 32,
          fontWeight: "bold" as const,
          color: "#FFFFFF",
          bgColor: "black@0.7",
          bgPadding: 14,
          shadow: false,
          outline: false,
        },
        animation: { entrance: "slide_left" as const, startSec: 0.5, durationSec: 8 },
      },
    ],
  },
  {
    id: "typewriter_intro",
    name: "Typewriter Intro",
    description: "Text appears character by character",
    category: "creative",
    layers: [
      {
        type: "text" as const,
        text: "Welcome to your new home...",
        position: { zone: "center" as const },
        style: {
          fontSize: 36,
          fontWeight: "bold" as const,
          color: "#FFFFFF",
          outlineColor: "#000000",
          outlineWidth: 2,
          shadow: true,
          outline: true,
        },
        animation: { entrance: "typewriter" as const, startSec: 0.5, durationSec: 6 },
      },
    ],
  },
  {
    id: "sticker_caption",
    name: "Sticker Caption",
    description: "White rounded card with text — social media style",
    category: "social",
    layers: [
      {
        type: "text" as const,
        text: "25 mins from Eko Atlantic 🏙️",
        position: { zone: "bottom" as const },
        style: {
          fontSize: 22,
          fontWeight: "bold" as const,
          color: "#1a1a1a",
          bgColor: "white@0.95",
          bgPadding: 14,
          bgRadius: 20,
          shadow: true,
          shadowColor: "black@0.2",
          outline: false,
        },
        animation: { entrance: "slide_bottom" as const, startSec: 1.5, durationSec: 4 },
      },
    ],
  },
  {
    id: "bold_cta",
    name: "Bold CTA",
    description: "Call-to-action with phone number and WhatsApp",
    category: "commercial",
    layers: [
      {
        type: "text" as const,
        text: "BOOK NOW",
        position: { zone: "bottom" as const },
        style: {
          fontSize: 40,
          fontWeight: "bold" as const,
          uppercase: true,
          color: "#FFFFFF",
          bgColor: "#22c55e@0.9",
          bgPadding: 16,
          bgRadius: 12,
          shadow: true,
          outline: false,
        },
        animation: { entrance: "pop_in" as const, startSec: 3, durationSec: 5 },
      },
      {
        type: "text" as const,
        text: "📞 +234 800 000 0000",
        position: { zone: "bottom" as const, y: 92 },
        style: {
          fontSize: 20,
          fontWeight: "normal" as const,
          color: "#FFFFFF",
          bgColor: "black@0.5",
          bgPadding: 8,
          bgRadius: 6,
          shadow: false,
          outline: false,
        },
        animation: { entrance: "fade_in" as const, startSec: 3.5, durationSec: 4.5, delay: 0.5 },
      },
    ],
  },
  {
    id: "feature_highlight",
    name: "Feature Highlight",
    description: "Animated feature callouts for property ads",
    category: "real_estate",
    layers: [
      {
        type: "text" as const,
        text: "✅ 24/7 Security",
        position: { zone: "free" as const, x: 10, y: 70 },
        style: {
          fontSize: 22,
          fontWeight: "bold" as const,
          color: "#FFFFFF",
          bgColor: "black@0.6",
          bgPadding: 10,
          bgRadius: 8,
          shadow: false,
          outline: false,
        },
        animation: { entrance: "slide_left" as const, startSec: 1, durationSec: 3 },
      },
      {
        type: "text" as const,
        text: "✅ Smart TV + Netflix",
        position: { zone: "free" as const, x: 10, y: 78 },
        style: {
          fontSize: 22,
          fontWeight: "bold" as const,
          color: "#FFFFFF",
          bgColor: "black@0.6",
          bgPadding: 10,
          bgRadius: 8,
          shadow: false,
          outline: false,
        },
        animation: { entrance: "slide_left" as const, startSec: 2, durationSec: 3 },
      },
      {
        type: "text" as const,
        text: "✅ Free Parking",
        position: { zone: "free" as const, x: 10, y: 86 },
        style: {
          fontSize: 22,
          fontWeight: "bold" as const,
          color: "#FFFFFF",
          bgColor: "black@0.6",
          bgPadding: 10,
          bgRadius: 8,
          shadow: false,
          outline: false,
        },
        animation: { entrance: "slide_left" as const, startSec: 3, durationSec: 3 },
      },
    ],
  },
];

export async function GET() {
  return NextResponse.json({ presets: PRESETS });
}
