// GioHomeStudio — Model Registry
// Source of truth for all available image and video generation models.
// UI reads from this registry. Gateways route based on provider + endpoint.
// No other file should call providers directly.

export interface ModelEntry {
  id: string;
  display_name: string;
  provider_name: "segmind" | "fal" | "runway" | "muapi" | "kling" | "kie";
  model_manufacturer: string;
  gateway: "segmind" | "fal" | "runway" | "muapi" | "kling" | "kie";
  endpoint_id: string;           // provider-specific model/endpoint identifier
  type: "image" | "image_edit" | "video";
  quality_tier: string;
  cost_to_henry: number;         // cost per generation in USD
  price_to_user: number;         // what user pays (future billing)
  profit_margin: number;         // price_to_user - cost_to_henry
  unit: string;                  // "per_image" | "per_clip" | "per_second"
  resolution: string;
  max_duration_seconds: number | null;
  avg_generation_seconds: number;
  is_free_tier_eligible: boolean;
  is_recommended_default: boolean;
  is_auto_selected_if_cheaper: boolean;
  tags: string[];
  strengths: string;
  best_for: string;
  sort_price_rank: number;       // lower = cheaper
  sort_quality_rank: number;     // higher = better quality
  sort_trending_score: number;
  sort_usage_count: number;
  is_active: boolean;
  notes: string;
}

// ── IMAGE MODELS ────────────────────────────────────────────────────────────

const IMAGE_MODELS: ModelEntry[] = [
  // ── Segmind ──
  {
    id: "segmind_pruna",
    display_name: "Pruna P Image",
    provider_name: "segmind",
    model_manufacturer: "Segmind",
    gateway: "segmind",
    endpoint_id: "p-image",
    type: "image",
    quality_tier: "budget",
    cost_to_henry: 0.005,
    price_to_user: 0.01,
    profit_margin: 0.005,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 5,
    is_free_tier_eligible: true,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["budget", "fast", "marketing"],
    strengths: "Lowest cost, fast iteration, good for marketing creatives",
    best_for: "Drafts, volume generation, cheap commercial images",
    sort_price_rank: 1,
    sort_quality_rank: 3,
    sort_trending_score: 80,
    sort_usage_count: 0,
    is_active: true,
    notes: "Verified working — p-image endpoint, $0.005/image",
  },
  {
    id: "segmind_pruna_edit",
    display_name: "Pruna P Image Edit",
    provider_name: "segmind",
    model_manufacturer: "Segmind",
    gateway: "segmind",
    endpoint_id: "p-image-edit",
    type: "image_edit",
    quality_tier: "budget",
    cost_to_henry: 0.005,
    price_to_user: 0.01,
    profit_margin: 0.005,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 6,
    is_free_tier_eligible: true,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["budget", "edit", "revision"],
    strengths: "Affordable edits, simple commercial revision flow",
    best_for: "Ad revisions, image cleanup, prompt-led edits",
    sort_price_rank: 1,
    sort_quality_rank: 3,
    sort_trending_score: 50,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },

  // ── fal.ai Image Models ──
  {
    id: "fal_flux_schnell",
    display_name: "Flux Schnell",
    provider_name: "fal",
    model_manufacturer: "Black Forest Labs",
    gateway: "fal",
    endpoint_id: "fal-ai/flux/schnell",
    type: "image",
    quality_tier: "budget_fast",
    cost_to_henry: 0.003,
    price_to_user: 0.008,
    profit_margin: 0.005,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 3,
    is_free_tier_eligible: true,
    is_recommended_default: true,
    is_auto_selected_if_cheaper: true,
    tags: ["fast", "budget", "general"],
    strengths: "Very fast, high quality at $0.003/image — best value",
    best_for: "Default for all generation — character, scene, commercial",
    sort_price_rank: 2,
    sort_quality_rank: 4,
    sort_trending_score: 90,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_flux_dev",
    display_name: "Flux Dev",
    provider_name: "fal",
    model_manufacturer: "Black Forest Labs",
    gateway: "fal",
    endpoint_id: "fal-ai/flux/dev",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.025,
    price_to_user: 0.04,
    profit_margin: 0.015,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 10,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["quality", "detailed", "versatile"],
    strengths: "Better detail than Schnell, still practical cost",
    best_for: "Quality images when budget matters",
    sort_price_rank: 5,
    sort_quality_rank: 6,
    sort_trending_score: 85,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_ideogram_v3_turbo",
    display_name: "Ideogram v3 Turbo",
    provider_name: "fal",
    model_manufacturer: "Ideogram",
    gateway: "fal",
    endpoint_id: "fal-ai/ideogram/v3/turbo",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.02,
    price_to_user: 0.035,
    profit_margin: 0.015,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 8,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["typography", "text", "branding", "posters"],
    strengths: "Best text rendering, excellent for ads with text",
    best_for: "Typography, flyers, posters, text-heavy branding",
    sort_price_rank: 4,
    sort_quality_rank: 7,
    sort_trending_score: 88,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_seedream",
    display_name: "Seedream",
    provider_name: "fal",
    model_manufacturer: "ByteDance",
    gateway: "fal",
    endpoint_id: "fal-ai/seedream",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.02,
    price_to_user: 0.035,
    profit_margin: 0.015,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 10,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["polished", "commercial", "modern"],
    strengths: "Polished commercial stills, stylized modern visuals",
    best_for: "Commercial stills, modern stylized content",
    sort_price_rank: 4,
    sort_quality_rank: 7,
    sort_trending_score: 75,
    sort_usage_count: 0,
    is_active: true,
    notes: "Verify exact fal endpoint",
  },
  {
    id: "fal_imagen4_fast",
    display_name: "Imagen 4 Fast",
    provider_name: "fal",
    model_manufacturer: "Google",
    gateway: "fal",
    endpoint_id: "fal-ai/imagen4/fast",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.02,
    price_to_user: 0.035,
    profit_margin: 0.015,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 8,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["google", "fast", "general"],
    strengths: "Google quality, fast turnaround",
    best_for: "General purpose high-quality images",
    sort_price_rank: 4,
    sort_quality_rank: 7,
    sort_trending_score: 70,
    sort_usage_count: 0,
    is_active: false,
    notes: "Verify exact fal endpoint availability",
  },
  {
    id: "fal_hunyuan",
    display_name: "Hunyuan",
    provider_name: "fal",
    model_manufacturer: "Tencent",
    gateway: "fal",
    endpoint_id: "fal-ai/hunyuan",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.02,
    price_to_user: 0.035,
    profit_margin: 0.015,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 12,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["chinese", "artistic", "versatile"],
    strengths: "Strong artistic generation, good text support",
    best_for: "Artistic content, varied styles",
    sort_price_rank: 4,
    sort_quality_rank: 6,
    sort_trending_score: 60,
    sort_usage_count: 0,
    is_active: false,
    notes: "Verify exact fal endpoint availability",
  },
  {
    id: "fal_nano_banana",
    display_name: "Nano Banana 2",
    provider_name: "fal",
    model_manufacturer: "fal",
    gateway: "fal",
    endpoint_id: "fal-ai/nano-banana-2",
    type: "image",
    quality_tier: "moderate_premium",
    cost_to_henry: 0.03,
    price_to_user: 0.05,
    profit_margin: 0.02,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 10,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "editing", "quality"],
    strengths: "Strong generation + editing capabilities",
    best_for: "Better output than cheap tiers, editing support",
    sort_price_rank: 6,
    sort_quality_rank: 8,
    sort_trending_score: 82,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_flux_pro",
    display_name: "Flux Pro",
    provider_name: "fal",
    model_manufacturer: "Black Forest Labs",
    gateway: "fal",
    endpoint_id: "fal-ai/flux-pro/v1.1",
    type: "image",
    quality_tier: "premium",
    cost_to_henry: 0.05,
    price_to_user: 0.08,
    profit_margin: 0.03,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 15,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "flagship", "best-quality"],
    strengths: "Top-tier Flux quality, best photorealism",
    best_for: "Final quality renders, hero images",
    sort_price_rank: 8,
    sort_quality_rank: 9,
    sort_trending_score: 92,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_flux_pro_ultra",
    display_name: "Flux Pro Ultra",
    provider_name: "fal",
    model_manufacturer: "Black Forest Labs",
    gateway: "fal",
    endpoint_id: "fal-ai/flux-pro/v1.1-ultra",
    type: "image",
    quality_tier: "premium_plus",
    cost_to_henry: 0.06,
    price_to_user: 0.10,
    profit_margin: 0.04,
    unit: "per_image",
    resolution: "2048x2048",
    max_duration_seconds: null,
    avg_generation_seconds: 20,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["ultra", "highest-quality", "large"],
    strengths: "Highest resolution, best detail",
    best_for: "Print quality, large format, maximum detail",
    sort_price_rank: 9,
    sort_quality_rank: 10,
    sort_trending_score: 78,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_ideogram_v3_quality",
    display_name: "Ideogram v3 Quality",
    provider_name: "fal",
    model_manufacturer: "Ideogram",
    gateway: "fal",
    endpoint_id: "fal-ai/ideogram/v3/quality",
    type: "image",
    quality_tier: "premium",
    cost_to_henry: 0.04,
    price_to_user: 0.07,
    profit_margin: 0.03,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 15,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "typography", "branding"],
    strengths: "High quality text rendering and branded graphics",
    best_for: "Polished branded graphics, text-heavy premium content",
    sort_price_rank: 7,
    sort_quality_rank: 9,
    sort_trending_score: 85,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_ideogram_v3_transparent",
    display_name: "Ideogram V3 Transparent",
    provider_name: "fal",
    model_manufacturer: "Ideogram",
    gateway: "fal",
    endpoint_id: "fal-ai/ideogram/v3/generate-transparent",
    type: "image",
    quality_tier: "standard",
    cost_to_henry: 0.030,
    price_to_user: 0.09,
    profit_margin: 0.060,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 8,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["transparent-background", "cutout", "logos", "products", "overlays", "png"],
    strengths: "Zero-background PNG output, best-in-class text rendering, ready to layer over video or image",
    best_for: "Product shots, logos, stickers, character cutouts — anything placed over a background",
    sort_price_rank: 6,
    sort_quality_rank: 7,
    sort_trending_score: 88,
    sort_usage_count: 0,
    is_active: true,
    notes: "Output is always PNG with alpha channel. Never convert to JPEG.",
  },
  {
    id: "fal_recraft_v3",
    display_name: "Recraft v3",
    provider_name: "fal",
    model_manufacturer: "Recraft",
    gateway: "fal",
    endpoint_id: "fal-ai/recraft-v3",
    type: "image",
    quality_tier: "premium",
    cost_to_henry: 0.04,
    price_to_user: 0.07,
    profit_margin: 0.03,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 12,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["design", "brand", "illustration"],
    strengths: "Design-style product graphics, illustration, branding",
    best_for: "Brand design, illustrations, product graphics",
    sort_price_rank: 7,
    sort_quality_rank: 8,
    sort_trending_score: 80,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },

  // ── Kie.ai Image Models ──
  {
    id: "kie_z_image_turbo",
    display_name: "Z-Image Turbo (Kie)",
    provider_name: "kie",
    model_manufacturer: "Kie.ai",
    gateway: "kie",
    endpoint_id: "z-image-turbo",
    type: "image",
    quality_tier: "budget_fast",
    cost_to_henry: 0.003,
    price_to_user: 0.008,
    profit_margin: 0.005,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 4,
    is_free_tier_eligible: true,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["budget", "fast", "photorealistic", "kie"],
    strengths: "Cheapest photorealistic model, very fast",
    best_for: "Volume generation, drafts, background scenes",
    sort_price_rank: 1,
    sort_quality_rank: 4,
    sort_trending_score: 85,
    sort_usage_count: 0,
    is_active: true,
    notes: "Free signup: 300 credits. Use as budget fallback when Segmind/fal rate-limit.",
  },
  {
    id: "kie_nano_banana_2",
    display_name: "Nano Banana 2 (Kie)",
    provider_name: "kie",
    model_manufacturer: "Kie.ai",
    gateway: "kie",
    endpoint_id: "nano-banana-2",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.04,
    price_to_user: 0.08,
    profit_margin: 0.04,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 8,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "photorealistic", "kie"],
    strengths: "High quality photorealistic output, consistent character renders",
    best_for: "Hero images, character portraits, product shots",
    sort_price_rank: 5,
    sort_quality_rank: 7,
    sort_trending_score: 75,
    sort_usage_count: 0,
    is_active: true,
    notes: "$0.04 per image via Kie.ai",
  },
  {
    id: "kie_gpt_image_1",
    display_name: "GPT-Image-1 (Kie)",
    provider_name: "kie",
    model_manufacturer: "OpenAI",
    gateway: "kie",
    endpoint_id: "gpt-image-1",
    type: "image",
    quality_tier: "moderate",
    cost_to_henry: 0.07,
    price_to_user: 0.14,
    profit_margin: 0.07,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 10,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["openai", "photorealistic", "instruction-following", "kie"],
    strengths: "Excellent instruction following, text in images, realistic scenes",
    best_for: "Ad creatives, product renders with text, precise scene control",
    sort_price_rank: 6,
    sort_quality_rank: 8,
    sort_trending_score: 90,
    sort_usage_count: 0,
    is_active: true,
    notes: "$0.02 low / $0.07 medium / $0.19 high quality. Registry uses medium ($0.07).",
  },
  {
    id: "kie_flux_kontext",
    display_name: "Flux Kontext (Kie)",
    provider_name: "kie",
    model_manufacturer: "Black Forest Labs",
    gateway: "kie",
    endpoint_id: "flux-kontext",
    type: "image_edit",
    quality_tier: "moderate",
    cost_to_henry: 0.03,
    price_to_user: 0.06,
    profit_margin: 0.03,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 8,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["edit", "flux", "context-aware", "kie"],
    strengths: "Context-aware image editing, style transfer, consistent edits",
    best_for: "Product image editing, background swaps, style changes",
    sort_price_rank: 4,
    sort_quality_rank: 7,
    sort_trending_score: 80,
    sort_usage_count: 0,
    is_active: true,
    notes: "Image editing via Kie.ai. Good for ad revision workflows.",
  },
  {
    id: "kie_midjourney_v7",
    display_name: "Midjourney V7 (Kie)",
    provider_name: "kie",
    model_manufacturer: "Midjourney",
    gateway: "kie",
    endpoint_id: "midjourney-v7",
    type: "image",
    quality_tier: "premium",
    cost_to_henry: 0.08,
    price_to_user: 0.18,
    profit_margin: 0.10,
    unit: "per_image",
    resolution: "1024x1024",
    max_duration_seconds: null,
    avg_generation_seconds: 15,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "artistic", "aesthetic", "midjourney", "kie"],
    strengths: "Best-in-class aesthetic quality, artistic renders, cinematic scenes",
    best_for: "Hero visuals, movie poster style, fashion and lifestyle imagery",
    sort_price_rank: 8,
    sort_quality_rank: 10,
    sort_trending_score: 95,
    sort_usage_count: 0,
    is_active: true,
    notes: "Midjourney V7 proxied via Kie.ai. Premium aesthetic tier.",
  },
];

// ── VIDEO MODELS ────────────────────────────────────────────────────────────

const VIDEO_MODELS: ModelEntry[] = [
  // ── Segmind Video ──
  {
    id: "segmind_pruna_video",
    display_name: "Pruna P Video",
    provider_name: "segmind",
    model_manufacturer: "Segmind",
    gateway: "segmind",
    endpoint_id: "p-video",
    type: "video",
    quality_tier: "budget",
    cost_to_henry: 0.005,
    price_to_user: 0.01,
    profit_margin: 0.005,
    unit: "per_clip",
    resolution: "720p",
    max_duration_seconds: 15,
    avg_generation_seconds: 10,
    is_free_tier_eligible: true,
    is_recommended_default: true,
    is_auto_selected_if_cheaper: true,
    tags: ["budget", "fast", "experimental"],
    strengths: "Cheapest video option, fast drafts",
    best_for: "Low-cost ideation, cheap early drafts, quick experiments",
    sort_price_rank: 1,
    sort_quality_rank: 2,
    sort_trending_score: 70,
    sort_usage_count: 0,
    is_active: true,
    notes: "3-15 second 720p clips ~10s generation",
  },

  // ── MuAPI Video Models (cheaper than FAL for same quality) ──
  {
    id: "muapi_seedance_lite",
    display_name: "Seedance Lite (MuAPI)",
    provider_name: "muapi",
    model_manufacturer: "ByteDance",
    gateway: "muapi",
    endpoint_id: "seedance-lite-i2v",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.020,
    price_to_user: 0.04,
    profit_margin: 0.02,
    unit: "per_clip",
    resolution: "480p",
    max_duration_seconds: 5,
    avg_generation_seconds: 45,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["seedance", "lite", "muapi", "cheap", "bytedance"],
    strengths: "Cheapest Seedance option — lite model for quick drafts",
    best_for: "Budget animated drafts before committing to Seedance Pro",
    sort_price_rank: 2,
    sort_quality_rank: 3,
    sort_trending_score: 76,
    sort_usage_count: 0,
    is_active: true,
    notes: "MuAPI Seedance Lite — cheaper lite version of Seedance Pro",
  },
  {
    id: "muapi_seedance_v1_pro",
    display_name: "Seedance 1.0 Pro (MuAPI)",
    provider_name: "muapi",
    model_manufacturer: "ByteDance",
    gateway: "muapi",
    endpoint_id: "seedance-pro-i2v",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.04,
    price_to_user: 0.07,
    profit_margin: 0.03,
    unit: "per_clip",
    resolution: "720p",
    max_duration_seconds: 5,
    avg_generation_seconds: 60,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["seedance", "muapi", "cheap", "bytedance"],
    strengths: "Cheap ByteDance Seedance via MuAPI — good motion quality",
    best_for: "Budget video generation, quick scene clips",
    sort_price_rank: 2,
    sort_quality_rank: 5,
    sort_trending_score: 80,
    sort_usage_count: 0,
    is_active: true,
    notes: "MuAPI Seedance 1.0 Pro — cheaper than FAL equivalent",
  },
  {
    id: "muapi_seedance_v2",
    display_name: "Seedance 2.0 (MuAPI)",
    provider_name: "muapi",
    model_manufacturer: "ByteDance",
    gateway: "muapi",
    endpoint_id: "seedance-v2.0-i2v",
    type: "video",
    quality_tier: "moderate_video",
    cost_to_henry: 0.08,
    price_to_user: 0.13,
    profit_margin: 0.05,
    unit: "per_clip",
    resolution: "720p",
    max_duration_seconds: 5,
    avg_generation_seconds: 90,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["seedance", "muapi", "bytedance", "quality"],
    strengths: "Seedance 2.0 — better motion and coherence than 1.0",
    best_for: "Good quality video at moderate cost via MuAPI",
    sort_price_rank: 4,
    sort_quality_rank: 6,
    sort_trending_score: 85,
    sort_usage_count: 0,
    is_active: true,
    notes: "MuAPI Seedance 2.0 — cheaper than FAL Seedance",
  },
  {
    id: "muapi_seedance_v2_1080p",
    display_name: "Seedance 2.0 1080p (MuAPI)",
    provider_name: "muapi",
    model_manufacturer: "ByteDance",
    gateway: "muapi",
    endpoint_id: "seedance-v2.0-i2v",
    type: "video",
    quality_tier: "moderate_video",
    cost_to_henry: 0.12,
    price_to_user: 0.19,
    profit_margin: 0.07,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 5,
    avg_generation_seconds: 120,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["seedance", "muapi", "1080p", "hd"],
    strengths: "Full HD Seedance 2.0 via MuAPI",
    best_for: "HD quality Seedance video at lower cost than FAL",
    sort_price_rank: 5,
    sort_quality_rank: 7,
    sort_trending_score: 82,
    sort_usage_count: 0,
    is_active: true,
    notes: "MuAPI Seedance 2.0 at 1080p resolution",
  },
  {
    id: "muapi_wan_v2_1_480p",
    display_name: "Wan 2.1 480p (MuAPI)",
    provider_name: "muapi",
    model_manufacturer: "Alibaba",
    gateway: "muapi",
    endpoint_id: "wan2.1-image-to-video",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.03,
    price_to_user: 0.06,
    profit_margin: 0.03,
    unit: "per_clip",
    resolution: "480p",
    max_duration_seconds: 5,
    avg_generation_seconds: 60,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["wan", "muapi", "cheap", "alibaba"],
    strengths: "Cheapest Wan option via MuAPI",
    best_for: "Fast cheap drafts, previews, testing motion",
    sort_price_rank: 2,
    sort_quality_rank: 4,
    sort_trending_score: 72,
    sort_usage_count: 0,
    is_active: true,
    notes: "MuAPI Wan 2.1 at 480p — very cheap draft quality",
  },
  {
    id: "muapi_wan_v2_1_720p",
    display_name: "Wan 2.1 720p (MuAPI)",
    provider_name: "muapi",
    model_manufacturer: "Alibaba",
    gateway: "muapi",
    endpoint_id: "wan2.1-image-to-video",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.05,
    price_to_user: 0.09,
    profit_margin: 0.04,
    unit: "per_clip",
    resolution: "720p",
    max_duration_seconds: 5,
    avg_generation_seconds: 90,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["wan", "muapi", "720p", "alibaba"],
    strengths: "Affordable HD Wan via MuAPI",
    best_for: "HD video drafts cheaper than FAL Wan Pro",
    sort_price_rank: 3,
    sort_quality_rank: 5,
    sort_trending_score: 74,
    sort_usage_count: 0,
    is_active: true,
    notes: "MuAPI Wan 2.1 at 720p",
  },

  // ── fal.ai Video Models ──
  {
    id: "fal_hailuo_standard",
    display_name: "Hailuo Standard",
    provider_name: "fal",
    model_manufacturer: "MiniMax",
    gateway: "fal",
    endpoint_id: "fal-ai/minimax/video-01",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.05,
    price_to_user: 0.08,
    profit_margin: 0.03,
    unit: "per_clip",
    resolution: "720p",
    max_duration_seconds: 6,
    avg_generation_seconds: 60,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["affordable", "video", "balanced"],
    strengths: "Cheap fal video option, decent motion",
    best_for: "Budget video when Segmind isn't enough quality",
    sort_price_rank: 3,
    sort_quality_rank: 4,
    sort_trending_score: 75,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_kling_2_5_standard",
    display_name: "Kling 2.5 Standard",
    provider_name: "fal",
    model_manufacturer: "Kuaishou",
    gateway: "fal",
    endpoint_id: "fal-ai/kling-video/v2.5/standard",
    type: "video",
    quality_tier: "moderate_video",
    cost_to_henry: 0.10,
    price_to_user: 0.15,
    profit_margin: 0.05,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 120,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["balanced", "quality", "kling"],
    strengths: "Good quality/cost balance, reliable motion",
    best_for: "Balanced quality video for commercials",
    sort_price_rank: 5,
    sort_quality_rank: 6,
    sort_trending_score: 85,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_hailuo_pro",
    display_name: "Hailuo Pro",
    provider_name: "fal",
    model_manufacturer: "MiniMax",
    gateway: "fal",
    endpoint_id: "fal-ai/minimax/video-01-pro",
    type: "video",
    quality_tier: "moderate_video",
    cost_to_henry: 0.15,
    price_to_user: 0.22,
    profit_margin: 0.07,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 6,
    avg_generation_seconds: 90,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["quality", "pro", "video"],
    strengths: "Better quality than standard, still moderate cost",
    best_for: "Quality upgrade from standard without premium price",
    sort_price_rank: 6,
    sort_quality_rank: 7,
    sort_trending_score: 72,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  // ── FAL LTX Video (ultra cheap open-source) ──
  {
    id: "fal_ltx_video",
    display_name: "LTX Video (FAL)",
    provider_name: "fal",
    model_manufacturer: "Lightricks",
    gateway: "fal",
    endpoint_id: "fal-ai/ltx-video/image-to-video",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.018,
    price_to_user: 0.04,
    profit_margin: 0.022,
    unit: "per_clip",
    resolution: "480p",
    max_duration_seconds: 5,
    avg_generation_seconds: 30,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["ltx", "fal", "cheap", "fast", "open-source", "disabled"],
    strengths: "Very cheap open-source model, fast generation",
    best_for: "DISABLED — times out at 30% on FAL server. Use Segmind Pruna instead.",
    sort_price_rank: 2,
    sort_quality_rank: 2,
    sort_trending_score: 72,
    sort_usage_count: 0,
    is_active: false,
    notes: "DISABLED — gets stuck at 30% and times out. Do not use.",
  },
  // ── FAL Wan Lite (cheap) ──
  {
    id: "fal_wan_lite",
    display_name: "Wan Lite 1.3B (FAL)",
    provider_name: "fal",
    model_manufacturer: "Alibaba",
    gateway: "fal",
    endpoint_id: "fal-ai/wan/v2.1/1.3b",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.025,
    price_to_user: 0.05,
    profit_margin: 0.025,
    unit: "per_clip",
    resolution: "480p",
    max_duration_seconds: 5,
    avg_generation_seconds: 60,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["wan", "fal", "cheap", "alibaba", "lite"],
    strengths: "Cheapest FAL option — Wan 1.3B lite, fast drafts",
    best_for: "Cheap quick previews when MuAPI is not preferred",
    sort_price_rank: 3,
    sort_quality_rank: 3,
    sort_trending_score: 75,
    sort_usage_count: 0,
    is_active: true,
    notes: "FAL Wan 2.1 1.3B — $0.025/clip at 480p, fast generation",
  },
  {
    id: "fal_wan_pro",
    display_name: "Wan Pro",
    provider_name: "fal",
    model_manufacturer: "Alibaba",
    gateway: "fal",
    endpoint_id: "fal-ai/wan/v2.1/pro",
    type: "video",
    quality_tier: "moderate_video",
    cost_to_henry: 0.12,
    price_to_user: 0.18,
    profit_margin: 0.06,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 120,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["quality", "alternative", "video"],
    strengths: "Quality alternative in moderate tier",
    best_for: "Alternative to Kling/Hailuo when different style needed",
    sort_price_rank: 5,
    sort_quality_rank: 6,
    sort_trending_score: 68,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_kling_2_5_turbo_pro",
    display_name: "Kling 2.5 Turbo Pro",
    provider_name: "fal",
    model_manufacturer: "Kuaishou",
    gateway: "fal",
    endpoint_id: "fal-ai/kling-video/v2.5/turbo-pro",
    type: "video",
    quality_tier: "premium_video",
    cost_to_henry: 0.20,
    price_to_user: 0.30,
    profit_margin: 0.10,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 60,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "fast", "kling"],
    strengths: "Fast premium Kling, turbo processing",
    best_for: "Quick premium video when time matters",
    sort_price_rank: 7,
    sort_quality_rank: 8,
    sort_trending_score: 88,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_kling_3_pro",
    display_name: "Kling 3.0 Pro",
    provider_name: "fal",
    model_manufacturer: "Kuaishou",
    gateway: "fal",
    endpoint_id: "fal-ai/kling-video/v3/pro",
    type: "video",
    quality_tier: "premium_video_plus",
    cost_to_henry: 0.30,
    price_to_user: 0.45,
    profit_margin: 0.15,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 180,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["flagship", "cinematic", "premium"],
    strengths: "Cinematic visuals, fluid motion, native audio",
    best_for: "Flagship final video, cinematic quality",
    sort_price_rank: 8,
    sort_quality_rank: 9,
    sort_trending_score: 95,
    sort_usage_count: 0,
    is_active: true,
    notes: "",
  },
  {
    id: "fal_runway_gen4",
    display_name: "Runway Gen-4",
    provider_name: "fal",
    model_manufacturer: "Runway",
    gateway: "fal",
    endpoint_id: "fal-ai/runway/gen4/turbo",
    type: "video",
    quality_tier: "premium_video_plus",
    cost_to_henry: 0.25,
    price_to_user: 0.40,
    profit_margin: 0.15,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 120,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["premium", "runway", "cinematic"],
    strengths: "Runway quality through fal gateway",
    best_for: "High quality video, cinematic scenes",
    sort_price_rank: 8,
    sort_quality_rank: 9,
    sort_trending_score: 90,
    sort_usage_count: 0,
    is_active: true,
    notes: "Runway via fal proxy",
  },
  {
    id: "runway_gen4_direct",
    display_name: "Runway Gen-4 (Direct)",
    provider_name: "runway",
    model_manufacturer: "Runway",
    gateway: "runway",
    endpoint_id: "gen4_turbo",
    type: "video",
    quality_tier: "premium_video_plus",
    cost_to_henry: 0.0,
    price_to_user: 0.0,
    profit_margin: 0.0,
    unit: "per_clip",
    resolution: "1280x720",
    max_duration_seconds: 10,
    avg_generation_seconds: 90,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["runway", "direct", "your-credits", "cinematic"],
    strengths: "Uses your Runway.com credits directly — not FAL proxy",
    best_for: "Spend your Runway account credits on high-quality Gen-4 video",
    sort_price_rank: 8,
    sort_quality_rank: 9,
    sort_trending_score: 92,
    sort_usage_count: 0,
    is_active: true,
    notes: "Direct Runway API — charges your Runway.com account credits",
  },
  {
    id: "fal_veo3_fast",
    display_name: "Veo 3 Fast",
    provider_name: "fal",
    model_manufacturer: "Google",
    gateway: "fal",
    endpoint_id: "fal-ai/veo3/fast",
    type: "video",
    quality_tier: "premium_video_plus",
    cost_to_henry: 0.25,
    price_to_user: 0.40,
    profit_margin: 0.15,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 8,
    avg_generation_seconds: 90,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["google", "premium", "fast"],
    strengths: "Google Veo quality, fast variant",
    best_for: "Premium video with faster turnaround",
    sort_price_rank: 8,
    sort_quality_rank: 9,
    sort_trending_score: 85,
    sort_usage_count: 0,
    is_active: false,
    notes: "Verify exact fal endpoint availability",
  },
  {
    id: "fal_veo3_4k",
    display_name: "Veo 3 4K",
    provider_name: "fal",
    model_manufacturer: "Google",
    gateway: "fal",
    endpoint_id: "fal-ai/veo3/4k",
    type: "video",
    quality_tier: "ultra_premium_video",
    cost_to_henry: 0.50,
    price_to_user: 0.80,
    profit_margin: 0.30,
    unit: "per_clip",
    resolution: "4K",
    max_duration_seconds: 8,
    avg_generation_seconds: 180,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["ultra", "4k", "google", "flagship"],
    strengths: "4K resolution, highest quality available",
    best_for: "Ultra-premium final renders, 4K output",
    sort_price_rank: 10,
    sort_quality_rank: 10,
    sort_trending_score: 80,
    sort_usage_count: 0,
    is_active: false,
    notes: "Verify exact fal endpoint availability",
  },

  // ── Kling Direct (api.klingai.com) ──────────────────────────────────────
  {
    id: "kling_direct_v2_5_std",
    display_name: "Kling 2.5 Standard ★ Direct",
    provider_name: "kling",
    model_manufacturer: "Kuaishou",
    gateway: "kling",
    endpoint_id: "kling-v2-master",
    type: "video",
    quality_tier: "moderate_video",
    cost_to_henry: 0.10,
    price_to_user: 0.14,
    profit_margin: 0.04,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 150,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["kling", "direct", "cinematic", "3d", "1080p"],
    strengths: "Direct Kling API — no FAL overhead, cinematic 3D motion",
    best_for: "Cinematic 3D scenes, realistic character animation",
    sort_price_rank: 5,
    sort_quality_rank: 8,
    sort_trending_score: 92,
    sort_usage_count: 0,
    is_active: true,
    notes: "Direct Kling API via KLING_ACCESS_KEY / KLING_SECRET_KEY",
  },
  {
    id: "kling_direct_v2_5_pro",
    display_name: "Kling 2.5 Pro ★ Direct",
    provider_name: "kling",
    model_manufacturer: "Kuaishou",
    gateway: "kling",
    endpoint_id: "kling-v2-master",
    type: "video",
    quality_tier: "premium_video",
    cost_to_henry: 0.20,
    price_to_user: 0.28,
    profit_margin: 0.08,
    unit: "per_clip",
    resolution: "1080p",
    max_duration_seconds: 10,
    avg_generation_seconds: 120,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: false,
    tags: ["kling", "direct", "pro", "premium", "cinematic"],
    strengths: "Premium Kling direct — best motion quality and consistency",
    best_for: "Final production renders, high-detail character scenes",
    sort_price_rank: 7,
    sort_quality_rank: 9,
    sort_trending_score: 90,
    sort_usage_count: 0,
    is_active: true,
    notes: "Kling v2.5 Pro mode via direct API",
  },
  {
    id: "kling_direct_v1_5_std",
    display_name: "Kling 1.6 Standard ★ Direct",
    provider_name: "kling",
    model_manufacturer: "Kuaishou",
    gateway: "kling",
    endpoint_id: "kling-v1-6",
    type: "video",
    quality_tier: "budget_video",
    cost_to_henry: 0.045,
    price_to_user: 0.07,
    profit_margin: 0.025,
    unit: "per_clip",
    resolution: "720p",
    max_duration_seconds: 10,
    avg_generation_seconds: 120,
    is_free_tier_eligible: false,
    is_recommended_default: false,
    is_auto_selected_if_cheaper: true,
    tags: ["kling", "direct", "budget", "720p"],
    strengths: "Cheaper Kling direct — good motion at lower cost",
    best_for: "Draft-quality Kling generation, testing scenes",
    sort_price_rank: 4,
    sort_quality_rank: 6,
    sort_trending_score: 78,
    sort_usage_count: 0,
    is_active: true,
    notes: "Kling v1.5 Standard via direct API",
  },
];

// ── Registry API ────────────────────────────────────────────────────────────

const ALL_MODELS = [...IMAGE_MODELS, ...VIDEO_MODELS];

export function getImageModels(activeOnly = true): ModelEntry[] {
  return IMAGE_MODELS.filter(m => !activeOnly || m.is_active);
}

export function getVideoModels(activeOnly = true): ModelEntry[] {
  return VIDEO_MODELS.filter(m => !activeOnly || m.is_active);
}

export function getAllModels(activeOnly = true): ModelEntry[] {
  return ALL_MODELS.filter(m => !activeOnly || m.is_active);
}

export function getModelById(id: string): ModelEntry | undefined {
  return ALL_MODELS.find(m => m.id === id);
}

export function getDefaultImageModel(): ModelEntry {
  const envDefault = process.env.DEFAULT_IMAGE_MODEL;
  if (envDefault) {
    const model = ALL_MODELS.find(m => m.id === envDefault && m.is_active);
    if (model) return model;
  }
  return IMAGE_MODELS.find(m => m.is_recommended_default && m.is_active) ?? IMAGE_MODELS[0];
}

export function getDefaultVideoModel(): ModelEntry {
  const envDefault = process.env.DEFAULT_VIDEO_MODEL;
  if (envDefault) {
    const model = ALL_MODELS.find(m => m.id === envDefault && m.is_active);
    if (model) return model;
  }
  return VIDEO_MODELS.find(m => m.is_recommended_default && m.is_active) ?? VIDEO_MODELS[0];
}
